repositoryUrl: https://github.com/dynamsoft-docs/barcode-reader-docs/blob/master
repository: dynamsoft-docs/barcode-reader-docs
docFullPath: https://www.dynamsoft.com/barcode-reader-review/docs/core/
firstLevelUrl: /barcode-reader-review/docs/core
docHomePage: /barcode-reader-review/docs/core/

useVersionTree: true

introduction: /barcode-reader-review/docs/core/introduction/
programming: /barcode-reader-review/docs/core/programming/
parameters: /barcode-reader-review/docs/core/parameters/
license_activation: /barcode-reader-review/docs/core/license-activation/
release_notes: /barcode-reader-review/docs/core/release-notes/
performance: /barcode-reader-review/docs/core/performance/
faq: /barcode-reader-review/docs/core/faq/
faq_general: /barcode-reader-review/docs/core/faq/general/

comparison_tools: /barcode-reader-review/docs/core/introduction/comparison-tools/

c: /barcode-reader-review/docs/server/programming/c/
c_api: /barcode-reader-review/docs/server/programming/c/api-reference/
c_methods: /barcode-reader-review/docs/server/programming/c/api-reference/methods/
c_release_notes: /barcode-reader-review/docs/server/programming/c/release-notes/

cpp: /barcode-reader-review/docs/server/programming/cplusplus/
cpp_api: /barcode-reader-review/docs/server/programming/cplusplus/api-reference/
cpp_methods: /barcode-reader-review/docs/server/programming/cplusplus/api-reference/cbarcodereader-methods/
cpp_release_notes: /barcode-reader-review/docs/server/programming/cplusplus/release-notes/

js: /barcode-reader-review/docs/web/programming/javascript/
js_api: /barcode-reader-review/docs/web/programming/javascript/api-reference/
js_release_notes: /barcode-reader-review/docs/web/programming/javascript/release-notes/

dotnet: /barcode-reader-review/docs/server/programming/dotnet/
dotnet_api: /barcode-reader-review/docs/server/programming/dotnet/api-reference/
dotnet_methods: /barcode-reader-review/docs/server/programming/dotnet/api-reference/BarcodeReader/
dotnet_class: /barcode-reader-review/docs/server/programming/dotnet/api-reference/class/
dotnet_release_notes: /barcode-reader-review/docs/server/programming/dotnet/release-notes/

oc: /barcode-reader-review/docs/mobile/programming/objectivec-swift/
oc_api: /barcode-reader-review/docs/mobile/programming/objectivec-swift/api-reference/
oc_release_notes: /barcode-reader-review/docs/mobile/programming/objectivec-swift/release-notes/
oc_methods: /barcode-reader-review/docs/mobile/programming/objectivec-swift/api-reference/methods/
oc_class: /barcode-reader-review/docs/mobile/programming/objectivec-swift/api-reference/class/
oc_methods: /barcode-reader-review/docs/mobile/programming/objectivec-swift/api-reference/methods/

java: /barcode-reader-review/docs/server/programming/java/
java_api: /barcode-reader-review/docs/server/programming/java/api-reference/
java_methods: /barcode-reader-review/docs/server/programming/java/api-reference/BarcodeReader/
java_class: /barcode-reader-review/docs/server/programming/java/api-reference/class/
java_release_notes: /barcode-reader-review/docs/server/programming/java/release-notes/

android: /barcode-reader-review/docs/mobile/programming/android/
android_api: /barcode-reader-review/docs/mobile/programming/android/api-reference/
android_release_notes: /barcode-reader-review/docs/mobile/programming/android/release-notes/
android_class: /barcode-reader-review/docs/mobile/programming/android/api-reference/class/
android_methods: /barcode-reader-review/docs/mobile/programming/android/api-reference/BarcodeReader/
  
python: /barcode-reader-review/docs/server/programming/python/
python_api: /barcode-reader-review/docs/server/programming/python/api-reference/
python_methods: /barcode-reader-review/docs/server/programming/python/api-reference/BarcodeReader/
python_class: /barcode-reader-review/docs/server/programming/python/api-reference/class/
python_release_notes: /barcode-reader-review/docs/server/programming/python/release-notes/

parameters_reference: /barcode-reader-review/docs/core/parameters/reference/
image_parameters: /barcode-reader-review/docs/core/parameters/reference/image-parameter/
scenario_settings: /barcode-reader-review/docs/core/parameters/scenario-settings/
enumerations: /barcode-reader-review/docs/core/parameters/enum/

faqs: /barcode-reader-review/docs/core/faq/
how_to: /barcode-reader-review/docs/core/faq/how-to-guide/

assets: /barcode-reader-review/docs/core/assets/
edit_icon: /barcode-reader-review/docs/core/assets/img-icon/edit-icon.png
smile_icon: /barcode-reader-review/docs/core/assets/img-icon/icon-smile.png
sad_icon: /barcode-reader-review/docs/core/assets/img-icon/icon-sad.png
dbr_icon: /barcode-reader-review/docs/core/assets/img-icon/icon-dbr.svg
dwt_icon: /barcode-reader-review/docs/core/assets/img-icon/icon-dwt.svg
dnt_icon: /barcode-reader-review/docs/core/assets/img-icon/icon-dnt.svg

baseurl: "/barcode-reader-review/docs/core"
plugins:
  - jemoji

edition: algorithm

defaults:
  - scope:
      path: ""
    values:
      category: "original-repo"
      edition: "algorithm"
  - scope:
      path: "web/programming/javascript"
    values:
      category: "js-repo"
      edition: "js"
  - scope:
      path: "mobile/programming/android"
    values:
      category: "mobile-repo"
      edition: "mobile"
  - scope:
      path: "mobile/programming/objectivec-swift"
    values:
      category: "mobile-repo"
      edition: "mobile"
  - scope:
      path: "server/programming/c"
    values:
      category: "original-repo"
      edition: "desktop"
  - scope:
      path: "server/programming/cplusplus"
    values:
      category: "original-repo"
      edition: "desktop"
  - scope:
      path: "server/programming/c-cplusplus"
    values:
      category: "original-repo"
      edition: "desktop"
  - scope:
      path: "server/programming/dotnet"
    values:
      category: "original-repo"
      edition: "desktop"
  - scope:
      path: "server/programming/python"
    values:
      category: "original-repo"
      edition: "desktop"
  - scope:
      path: "server/programming/java"
    values:
      category: "original-repo"
      edition: "desktop"
  - scope:
      path: ""
    values:
      layout: "default-layout"
      noTitleIndex: true
      needAutoGenerateSidebar: true
      needGenerateH3Content: true

url: "https://www.dynamsoft.com" # sitemap root
