# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the master branch
  #push:
 #   branches: 
    - master 
    - preview 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains jobs called "Build-Main" and "Build-Preview"
  Build-Main:
    if: ${{ github.ref == 'refs/heads/master' }}
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Build the site
        run: |
          cd /home/ubuntu
          [ ! -d DBRDocCore ] && mkdir -p DBRDocCore
          [ ! -d barcode-reader-docs ] && git clone --depth 1 https://github.com/dynamsoft-docs/barcode-reader-docs.git barcode-reader-docs
          [ ! -d Docs-Template-Repo-Preview ] && git clone --depth 1 --branch preview https://github.com/dynamsoft-docs/Docs-Template-Repo.git Docs-Template-Repo-Preview
          cd barcode-reader-docs && git pull && cd .. && cp -rfp ./barcode-reader-docs/* ./DBRDocCore/
          cd Docs-Template-Repo-Preview && git pull && cd .. && cp -rfp ./Docs-Template-Repo-Preview/* ./DBRDocCore/
          cd DBRDocCore && bundle exec jekyll build --incremental
          python3 /home/ubuntu/ftp.py /home/ubuntu/DBRDocCore/_site/ ./www.dynamsoft.com/barcode-reader/docs/core/ prod

  Build-Preview:
    if: ${{ github.ref == 'refs/heads/preview' }}
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Build the site
        run: |
          cd /home/ubuntu
          [ -d DBRDocCoreFull ] && rm -rf DBRDocCoreFull 
          [ -d Docs-Template-Repo-Preview2 ] && rm -rf Docs-Template-Repo-Preview2
          [ ! -d DBRDocCore-preview ] && mkdir -p DBRDocCore-preview
          [ ! -d barcode-reader-docs-preview ] && git clone --depth 1 --branch preview https://github.com/dynamsoft-docs/barcode-reader-docs.git barcode-reader-docs-preview
          [ ! -d Docs-Template-Repo-Preview ] && git clone --depth 1 --branch preview https://github.com/dynamsoft-docs/Docs-Template-Repo.git Docs-Template-Repo-Preview
          cd barcode-reader-docs-preview && git pull && cd .. && cp -rfp ./barcode-reader-docs-preview/* ./DBRDocCore-preview/
          cd Docs-Template-Repo-Preview && git pull && cd .. && cp -rfp ./Docs-Template-Repo-Preview/* ./DBRDocCore-preview/
          sed -i -e "1,3s/blob\/master$/blob\/preview/" \
          -e "1,3s/blob\/main$/blob\/preview/" /home/ubuntu/DBRDocCore-preview/_config.yml
          cd DBRDocCore-preview && bundle exec jekyll build --incremental && cd ..

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_TEST_SITE_SERVER }}
          username: ${{ secrets.FTP_TEST_SITE_USER }}
          password: ${{ secrets.FTP_TEST_SITE_PASSWORD }}
          port: 7500 
          local-dir: /home/ubuntu/DBRDocCore-preview/_site/
          server-dir: /www.dynamsoft.com/barcode-reader/docs/core/
          